### ISSUE TITLE
Port to tensorflow.js

### ISSUE THREAD

**Issue by MariasStory** [saeed-anwar/RIDNet#2]
Hi @saeed-anwar,
Thank you for this code. I did not test it yet.

Am I right that your denoising model is only 5MB?
If so, it seems to be a very light model and can be ported to javascript.
Can you please check if it is possible to convert your model to tensoflow.js?

I have to admit that I am confused by your code in "RIDNet/TestCode/code/main.py":
        t.train()
        t.test()
is it a training code?

Please confirm that I can simply denoise my own image with the command you provided to "test the algorithm".

**Comment by saeed-anwar** [comment]
Yes, it is 5MB. 
Sorry haven't checked whether it is convertable to tensorflow.js. If pytorch models are convertible, then it will also be convertable.

The code can train and test. However, the particular settings are specific to testing. 
Yes, you can test your own images. Follow the structure of the image directory provided.

**Comment by MariasStory** [comment]
Maybe something linke: https://drsleep.github.io/Tutorial-PyTorch-to-TensorFlow-JS/

**Comment by saeed-anwar** [comment]
Seems difficult for time being to perform this process.
