### ISSUE TITLE
train/valid sets

### ISSUE THREAD

**Issue by eastchun** [saeed-anwar/RIDNet#3]
Hi Saeed,

Could you share your RIDNet training environment?

- Synthetic noise generation: AWGN only?
- Training configuration: One epoch for synthetic noise followed by another epoch of real noise?
- Total number of 80x80 patches for synthetic noise images and real-noise patches (respectively)?
- Total number of epochs for training?

BR/ East

**Comment by saeed-anwar** [comment]
Hi,

I will post the training environment as well, it requires a little bit of cleaning. Just busy in some other projects.
