### ISSUE TITLE
data

### ISSUE THREAD

**Issue by juingzhou** [saeed-anwar/RIDNet#5]
hi
First, can you provide download links to all training datasets?
Second, can you provide the following details of training data set preprocessing?

**Comment by saeed-anwar** [comment]
There is no special data preprocessing for training data. Only subtraction and addition is performed in the network which you can see in the network.

The training datasets named in the paper. Just search using the name of the dataset will come up.
Unfortunately, I don't have the exact links.

**Comment by juingzhou** [comment]
thanks
