### ISSUE TITLE
self.ckp.log[-1, idx_scale] = eval_acc / len(self.loader_test) ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by SreeHarshaNelaturu** [saeed-anwar/RIDNet#8]
Making model...
Loading model from ../experiment/ridnet.pt

Evaluation:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    while not t.terminate():
  File "/home/User/Documents/ridnet/RIDNet/TestCode/code/trainer.py", line 139, in terminate
    self.test()
  File "/home/User/Documents/ridnet/RIDNet/TestCode/code/trainer.py", line 110, in test
    self.ckp.log[-1, idx_scale] = eval_acc / len(self.loader_test)
ZeroDivisionError: division by zero

I noticed this error had been brought up earlier, but there was no fix that I could find in the thread. Could you please let me know how I could go about fixing this error?

PyTorch : 0.4.1
Python : 3.6.3
CPU

**Comment by saeed-anwar** [comment]
Check the path for your testing images.

**Comment by SreeHarshaNelaturu** [comment]
I'm using the default command

python main.py --data_test MyImage --noise_g 1 --model RIDNET --n_feats 64 --pre_train ../experiment/ridnet.pt --test_only --save_results --save 'RIDNET_RNI15' --testpath ../LR/LRBI/ --testset RNI15 --cpu 

This is to test with the default test present in LR/LRBI/RNI_15/X1 without any additions/changes.

This is right after cloning the repository and adding ridnet.pt to experiment. 
Could you let me know what I could change?

**Comment by SreeHarshaNelaturu** [comment]
Solution : 
pip install scipy==1.1.0
scipy.misc is removed after scipy 1.2.0 and that's why the images are not being read.

If you could add this to requirements would be great.
